### ISSUE TITLE
对于element 的Table Events不支持

### ISSUE THREAD

**Issue by SaberInoryKiss** [cloydlau/elastic-list#1]
如题，element的Table 方法如select等，并没有通过elTableProps生效，能请问一下，这个需要怎么配么？
![image](https://user-images.githubusercontent.com/39288809/103201847-e8051280-492b-11eb-8876-fb67a2ea68e5.png)

**Comment by cloydlau** [comment]
你好 文档里有提到监听el-table事件：

  ```
  <ElasticList ref="elasticList"/>
  
  this.$refs.elasticList.$children[0].$on('row-click', e => {
    console.log(e)
  })
  ```

不过这样的方式非常不好 下个版本我会优化

**Comment by SaberInoryKiss** [comment]
> 你好 文档里有提到监听el-table事件：
> 
> ```
> <ElasticList ref="elasticList"/>
> 
> this.$refs.elasticList.$children[0].$on('row-click', e => {
>   console.log(e)
> })
> ```
> 
> 不过这样的方式非常不好 下个版本我会优化

好嘞，感谢

**Comment by SaberInoryKiss** [comment]
> 你好 文档里有提到监听el-table事件：
> 
> ```
> <ElasticList ref="elasticList"/>
> 
> this.$refs.elasticList.$children[0].$on('row-click', e => {
>   console.log(e)
> })
> ```
> 
> 不过这样的方式非常不好 下个版本我会优化

你好，我有个疑问哈，在输入框内拖动时，我看文档是默认在输入框内不触发排序，但是我这边引用后，输入框拖动仍然触发排序了，我只做了如下设置：
`<ElasticList   
        ref="relyonTable" 
        v-model='relyonTable'
        :elTableProps="{
          border: true,
          fit: true,
          stripe: true,
          highlightCurrentRow: true,
        }"
        width=80%>`

**Comment by cloydlau** [comment]
v0.1.3已发布🎉

1. 监听el-table事件用法和el-table保持一致：```<ElasticList @row-click="onRowClick"/>```
2. 新增对删除动画的配置
